config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users

  # Goal routes nested under user
  resources :users do
    resources :goals
  end

  # Activity routes nested under goal
  resources :goals do
    resources :activities
  end

  # Reminder routes nested under goal
  resources :goals do
    resources :reminders
  end

  # Community routes
  resources :communities
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :goal

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
end

app/models/community_membership.rb
class CommunityMembership < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :date, presence: true
  validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :goals, dependent: :destroy
  has_many :activities, through: :goals
  has_many :reminders, through: :goals

  # has_secure_password

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :goal_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  def index
    @communities = Community.all
  end

  def show
  end

  def new
    @community = Community.new
  end

  def edit
  end

  def create
    @community = Community.new(community_params)

    if @community.save
      redirect_to @community, notice: 'Community was successfully created.'
    else
      render :new
    end
  end

  def update
    if @community.update(community_params)
      redirect_to @community, notice: 'Community was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @community.destroy
    redirect_to communities_url, notice: 'Community was successfully destroyed.'
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_params
    params.require(:community).permit(:name, :description, :location)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :authenticate_user!

  def index
    @goals = current_user.goals
  end

  def new
    @goal = current_user.goals.build
  end

  def create
    @goal = current_user.goals.build(goal_params)
    if @goal.save
      redirect_to @goal, notice: 'Goal created successfully.'
    else
      render :new
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :description, :deadline, :status)
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def new
    @reminder = Reminder.new
  end

  def create
    @reminder = current_user.reminders.build(reminder_params)
    if @reminder.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def reminder_params
    params.require(:reminder).permit(:name, :date, :time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
    @activities = @user.activities
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= form_with model: @goal, url: goal_path(@goal), method: :patch do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :deadline %>
  <%= form.datetime_select :deadline %>

  <%= form.label :status %>
  <%= form.select :status, options_for_select([['Not started', 'not_started'], ['In progress', 'in_progress'], ['Completed', 'completed']], @goal.status) %>

  <%= form.submit %>
<% end %>

<p><%= link_to 'Back', goals_path %></p>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= form_with(model: @goal, local: true) do |form| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :goal_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :goal_description %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline, id: :goal_deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @goal.deadline.strftime('%m/%d/%Y') %>
</p>

<h2>Activities</h2>

<ul>
  <% @goal.activities.each do |activity| %>
    <li>
      <%= activity.name %> - <%= activity.status %>
    </li>
  <% end %>
</ul>

<h2>Reminders</h2>

<ul>
  <% @goal.reminders.each do |reminder| %>
    <li>
      <%= reminder.title %> - <%= reminder.body %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWorkLifeBalanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with model: @user, url: users_path do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_digest %>
    <%= form.password_field :password_digest, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Register", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>Goals</h2>
<% if @user.goals.any? %>
  <ul>
    <% @user.goals.each do |goal| %>
      <li><%= goal.name %> - <%= goal.description %></li>
    <% end %>
  </ul>
<% else %>
  <p>No goals found for this user.</p>
<% end %>
<h2>Activities</h2>
<% if @user.activities.any? %>
  <ul>
    <% @user.activities.each do |activity| %>
      <li><%= activity.name %> - <%= activity.description %></li>
    <% end %>
  </ul>
<% else %>
  <p>No activities found for this user.</p>
<% end %>